language: python

dist: xenial

python:
  - "3.6"
  - "3.7"
  - "3.8"

addons:
  apt:
    packages:
      - libgconf-2-4

env:
  - CYPRESS_VIDEO=false
    DOCKER_PLATFORM=linux/386,linux/arm64,linux/amd64,linux/arm/v7,linux/arm/v6 
    TARGET_IMAGE=delfick/lifx-photons-interactor

install:
  - pip install pip --upgrade
  - pip install -e "modules[tests]"
  - pip install -e "apps/interactor"

script:
  - cd modules && ./test.sh -v
  - cd ../apps/interactor && ./test.sh

jobs:
  include:
    - stage: deploy
      script: skip
      addons: skip
      install: skip
      before_script: skip
      before_deploy: skip

      if: tag IS present

      deploy:
        provider: script
        skip_cleanup: true
        on:
          tags: true

        script: ./apps/interactor/docker/create_container.sh
