---

context:
  use_gitignore: true

image_index: delfick/

images:
  lifx-photons-interactor:
    context:
      parent_dir: "{config_root}/../../../"

    commands:
      - FROM python:3.8.1-slim

      - - RUN
        - apt-get update
          && apt-get install gcc -y
          && rm -rf /var/lib/apt/lists/*

      - ADD apps/interactor/command /project/
      - ADD apps/interactor /project/interactor
      - ADD modules /project/modules

      - WORKDIR /project/config

      - RUN pip install pip -U && pip install /project/modules /project/interactor

      - ENV INTERACTOR_HOST 0.0.0.0
      - CMD lifx lan:interactor
